"""Skema Awal Final

Revision ID: f56440d759af
Revises: 
Create Date: 2025-06-21 14:56:31.118599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56440d759af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_bahan', sa.String(length=250), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_bahan')
    )
    with op.batch_alter_table('bahan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bahan_kategori'), ['kategori'], unique=False)

    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('resep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('deskripsi_singkat', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pengguna_id', 'resep_id', name='unique_pengguna_resep')
    )
    op.create_table('langkah_memasak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('nomor_langkah', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resep_bahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resep_id', sa.Integer(), nullable=False),
    sa.Column('bahan_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.String(length=50), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bahan_id'], ['bahan.id'], ),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayatpencarian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayatpencarian')
    op.drop_table('resep_bahan')
    op.drop_table('langkah_memasak')
    op.drop_table('favorit')
    op.drop_table('resep')
    op.drop_table('pengguna')
    with op.batch_alter_table('bahan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bahan_kategori'))

    op.drop_table('bahan')
    # ### end Alembic commands ###
